export const ADD_PLAYER_HAND, = ' ADD_PLAYER_HAND';
export const ADD_PLAYER_SETS, = ' ADD_PLAYER_SETS';
export const PLAYER_DRAW_CARD, = ' PLAYER_DRAW_CARD';
export const PLAYER_DRAW_TO, = ' PLAYER_DRAW_TO';
export const SCRAP_CARDS, = 'SCRAP_CARDS';
export const SET_PLAYER_HAND, = 'SET_PLAYER_HAND';
export const SET_PLAYER_ID, = 'SET_PLAYER_ID';
export const SET_PLAYER_NAME, = 'SET_PLAYER_NAME';
export const SET_PLAYER_SETS, = 'SET_PLAYER_SETS';
export const UPDATE_PLAYER, = ' UPDATE_PLAYER';

export const PLAYER_ACTIONS =new Set([ADD_PLAYER_HAND,
ADD_PLAYER_SETS,
PLAYER_DRAW_CARD,
PLAYER_DRAW_TO,
SCRAP_CARDS,
SET_PLAYER_HAND,
SET_PLAYER_ID,
SET_PLAYER_NAME,
SET_PLAYER_SETS,
UPDATE_PLAYER,])
